CREATE TABLE metrics(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  request_id UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
  route VARCHAR(100) NOT NULL,
  method VARCHAR(100) NOT NULL,
  complexity VARCHAR(50) NOT NULL,
  n_param INTEGER DEFAULT 0 NOT NULL,
  response_ms DECIMAL(10,5) NOT NULL,
  status_code INTEGER NOT NULL,
  error_message VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_metrics_route       ON metrics(route);
CREATE INDEX idx_metrics_complexity  ON metrics(complexity);
CREATE INDEX idx_metrics_requested   ON metrics(created_at);
CREATE INDEX idx_metrics_n_param     ON metrics(n_param);
